name: sportify
description: Mobile application for sports news and more.
homepage: https://github.com/antoniocranga/sportify
publish_to: 'none'
version: 0.0.2

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.4

  cloud_firestore: ^4.5.1
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  envied: ^0.3.0
  dio: ^5.1.1
  equatable: ^2.0.5
  intl: ^0.17.0
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
